version: "3"

services:
  webserver:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshop_user
      MYSQL_PASSWORD: admin
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: admin
